LABEL maintainer="Christian Felder"
LABEL RUN="podman run --rm --cap-drop=all --cap-add=chown --cap-add=setuid --cap-add=setgid --cap-add=setpcap --cap-add=audit_control --cap-add=dac_override --cap-add=fowner -P --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d IMAGE"

WORKDIR /root

RUN dnf install -y epel-release \
  && dnf -y update-minimal --setopt=tsflags=nodocs \
      --security --sec-severity=Important --sec-severity=Critical \
  && dnf -y group install --setopt=tsflags=nodocs xfce-desktop \
  && dnf -y install --setopt=tsflags=nodocs xfce4-notifyd tigervnc-server \
  && dnf clean all -y

COPY entrypoint.sh /
COPY startxfce4.bash /usr/bin/
COPY xfce4-screensaver.xml /usr/share/xfce4/xfconf/xfce-perchannel-xml/
COPY xfce4-desktop.xml /usr/share/xfce4/xfconf/xfce-perchannel-xml/
COPY restart_on_success.conf /etc/systemd/system/vncserver\@.service.d/
EXPOSE 5901/tcp

VOLUME ["/config"]

ENV USER_ID=10000
ENV USER="container"
ENV VNCPASSWD="pod.VNC"
ENV VNCRESOLUTION="1280x720"
ENV BACKGROUND="/usr/share/backgrounds/images/default.png"
ENV DESKTOP="/config/desktop"
ENV STARTXFCE4="startxfce4.bash"

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/sbin/init"]
